### ISSUE TITLE
Problem dublicate events

### ISSUE THREAD

**Issue by onword333** [stape-io/data-tag#1]
Hello. Please help.
Why do I have duplicate events?
When I click on publish web container events come. Why ?

I use Data-tag(this from this rep) and Data-client (https://github.com/gtm-server/data-client)

video
https://drive.google.com/file/d/1CCiBbhZsN8g4XQUJ7dq5fU9XgCYnn6F7/view?usp=sharing

**Comment by Bukashk0zzz** [comment]
This issue is closed in favor of the same question in the community.
Please create issues in one place.

 https://community.stape.io/t/events-are-triggered-when-publish-a-web-container/126
