### ISSUE TITLE
"still running"

### ISSUE THREAD

**Issue by ASomerN** [stape-io/data-tag#2]
The tag is not firing, when in preview mode and attempting to send all data from the dataLayer the status of the tag is "still running".

There's no logging for me to supply more context:

![image](https://user-images.githubusercontent.com/29146770/136197335-b08816c6-97ed-4252-9e4e-f571d8c96b96.png)

I can see the network request for the script from: https://cdn.stape.io/dtag/v2.js
There's no post or get requests being made to the desired endpoint using the latest version of this tag.

calling dataTagSendData({"event":"test"},"myendpoint") from console works.

It appears that when turning off "Send al from DataLayer" the tag works

**Comment by ASomerN** [comment]
This particular issue was caused by non-standard objects in the dataLayer. I've updated the function that maps the dataLayer so that it only looks for objects with an event key:

```
function addDataLayerDataForPostRequest(data, eventData) {
    if (data.add_data_layer) {
        const gtmId = copyFromDataLayer('gtm.uniqueEventId');
        const dataLayer = copyFromWindow('dataLayer');

        if (dataLayer && gtmId) {
            let obj = dataLayer.filter((o) => { 
                return typeof o.event !== "undefined";
                }).map(o => {
                if (o['gtm.uniqueEventId']) return o;

                o = JSON.parse(JSON.stringify(o));

                for (let prop in o) {
                    return o[prop];
                }
            }).filter(o => {
                if (o['gtm.uniqueEventId'] === gtmId) return true;
            });

            if (obj.length) {
                obj = obj[0];

                for (let objKey in obj) {
                    eventData[objKey] = obj[objKey];
                }
            }
        }
    }
    return eventData;
}
```

**Comment by Bukashk0zzz** [comment]
Thanks for the detailed bug report and fix. 
I updated Data Tag and push the needed changes to Community Gallery.
